services:
  db:
    image: postgres:15-alpine
    container_name: projeto-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: musical
    ports:
      - "5432:5432" 
    volumes:
      - ./db/schema/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./back-end  
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/musical
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=adminpassword

  frontend:
    build: ./front-end 
    ports:
      - "5173:80"      
    depends_on:
      - backend

volumes:
  postgres_data: